# frontend-image-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-image
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-image
  template:
    metadata:
      labels:
        app: frontend-image
    spec:
      containers:
        - name: frontend-image
          image:  [REDACTED]

          
